/**
 * Committed connection artifacts + drift parity (E3-C4 / issue #140).
 *
 * The connect layer's output (edge-mint #137 → conflation #138 → SoR-precedence
 * #139) is persisted as deterministic, committed git artifacts so it becomes a
 * reviewable, diff-stable record. This module is the pure heart: it runs the
 * three engines in order, serializes their output canonically, writes the
 * generated artifacts, and provides a byte-for-byte `--check` parity gate that
 * mirrors `derive --check`.
 *
 * INPUT vs OUTPUT — a hard distinction enforced here:
 *
 *  • `manual-overrides.json` is human-authored INPUT. It is the *only* place an
 *    operator (or a reviewed LLM suggestion) may steer the connect result, and
 *    `connect` NEVER writes or overwrites it. Overrides are applied as synthetic
 *    {@link KBNode.identityClaims} / {@link KBNode.linkedRefs} injected onto the
 *    in-memory graph BEFORE the engines run, so they flow through the SAME,
 *    unchanged engines: a `same-as` override forces a conflation, a
 *    `differentiated-from` override blocks one, a `linkedRef` override mints an
 *    edge. The engines (#137/#138/#139) are not modified.
 *
 *  • `minted-edges.json`, `conflation-map.json`, `precedence-map.json` are
 *    generated OUTPUT — regenerated wholesale by `connect`, never hand-edited.
 *    Each is serialized with {@link canonicalStringify} (sorted keys, trailing
 *    newline, NO timestamps), so identical inputs ⇒ byte-identical files and the
 *    drift check is meaningful.
 *
 * Note on format: the issue names `manual-overrides.yaml`; this implementation
 * uses `manual-overrides.json` deliberately — the repo is JSON-based with no
 * YAML dependency, and a bespoke YAML subset parser is a latent-bug source. A
 * human-authored JSON file is equally reviewable and zero-risk.
 *
 * @module lib/connect
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import type {
  IdentityClaim,
  IdentityClaimKind,
  KBConfig,
  KBEdge,
  KBGraph,
  KBNode,
  SourcePrecedenceConfig,
  SourceRef,
} from '@anokye-labs/kbexplorer-core';
import { canonicalStringify } from './jsonld.ts';
import { mintReferenceEdges } from './edge-mint.ts';
import { conflateReferents } from './conflation.ts';
import { resolvePrecedence } from './precedence.ts';

/** Directory (repo-relative) holding the committed connection artifacts. */
export const CONNECT_DIR = '.kbx/connection';
/** Generated output artifact filenames (regenerated by `connect`). */
export const MINTED_EDGES_FILE = 'minted-edges.json';
export const CONFLATION_MAP_FILE = 'conflation-map.json';
export const PRECEDENCE_MAP_FILE = 'precedence-map.json';
/** The three generated artifacts, sorted. */
export const ARTIFACT_FILES = Object.freeze([
  CONFLATION_MAP_FILE,
  MINTED_EDGES_FILE,
  PRECEDENCE_MAP_FILE,
]);
/** Human-authored INPUT override file — never written by `connect`. */
export const OVERRIDES_FILE = 'manual-overrides.json';

/** Error carrying a stable `.code` for connect-layer failures. */
export class ConnectError extends Error {
  code: string;

  constructor(message: string, code = 'CONNECT_ERROR') {
    super(message);
    this.name = 'ConnectError';
    this.code = code;
  }
}

interface OverrideIdentityClaim {
  node: string;
  claim: IdentityClaimKind;
  ref: string | Partial<SourceRef>;
  source?: string;
  basis?: string;
}

interface OverrideLinkedRef {
  node: string;
  ref?: string | Partial<SourceRef>;
  href?: string;
  resourceKind?: string;
  role?: string;
}

interface NormalizedOverrides {
  identityClaims: OverrideIdentityClaim[];
  linkedRefs: OverrideLinkedRef[];
}

interface RunConnectOptions {
  overrides?: NormalizedOverrides | null;
  config?: KBConfig;
  precedence?: SourcePrecedenceConfig;
}

interface ConnectGraph {
  nodes?: KBNode[];
  edges?: KBEdge[];
  [key: string]: unknown;
}

interface PrecedenceInfo {
  resolved?: Record<string, unknown>;
  conflicts?: Record<string, unknown>;
}

interface PrecedenceEntry {
  node: string;
  resolved?: Record<string, unknown>;
  conflicts?: Record<string, unknown>;
}

interface RunConnectResult {
  graph: ReturnType<typeof resolvePrecedence>['graph'];
  minted: ReturnType<typeof mintReferenceEdges>['minted'];
  groups: ReturnType<typeof conflateReferents>['groups'];
  warnings: ReturnType<typeof conflateReferents>['warnings'];
  precedenceMap: PrecedenceEntry[];
  stats: {
    mintedEdges: number;
    conflatedGroups: number;
    contradictions: number;
    precedenceResolved: number;
    precedenceConflicts: number;
  };
}

type ArtifactStatus = 'created' | 'updated' | 'unchanged';

function cmp(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * Normalize a raw parsed override document into `{ identityClaims, linkedRefs }`
 * arrays. Unknown top-level keys are ignored; a missing section is an empty
 * array. Shape is validated just enough to fail loudly on obviously wrong input.
 *
 * @param {unknown} raw
 * @returns {{ identityClaims: object[], linkedRefs: object[] }}
 */
export function normalizeOverrides(raw: unknown): NormalizedOverrides {
  if (raw == null) return { identityClaims: [], linkedRefs: [] };
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    throw new ConnectError('manual-overrides.json must be a JSON object.', 'OVERRIDES_INVALID');
  }
  const value = raw as { identityClaims?: unknown; linkedRefs?: unknown };
  const identityClaims = value.identityClaims ?? [];
  const linkedRefs = value.linkedRefs ?? [];
  if (!Array.isArray(identityClaims) || !Array.isArray(linkedRefs)) {
    throw new ConnectError(
      'manual-overrides.json: `identityClaims` and `linkedRefs` must be arrays.',
      'OVERRIDES_INVALID'
    );
  }
  for (const o of identityClaims) {
    if (
      !o ||
      typeof o !== 'object' ||
      typeof (o as OverrideIdentityClaim).node !== 'string' ||
      typeof (o as OverrideIdentityClaim).claim !== 'string' ||
      (o as OverrideIdentityClaim).ref == null
    ) {
      throw new ConnectError(
        'manual-overrides.json: each identityClaims entry needs `node`, `claim`, and `ref`.',
        'OVERRIDES_INVALID'
      );
    }
  }
  for (const o of linkedRefs) {
    if (
      !o ||
      typeof o !== 'object' ||
      typeof (o as OverrideLinkedRef).node !== 'string' ||
      (typeof (o as OverrideLinkedRef).ref !== 'string' && (o as OverrideLinkedRef).href == null)
    ) {
      throw new ConnectError(
        'manual-overrides.json: each linkedRefs entry needs `node` and `ref`/`href`.',
        'OVERRIDES_INVALID'
      );
    }
  }
  return {
    identityClaims: identityClaims as OverrideIdentityClaim[],
    linkedRefs: linkedRefs as OverrideLinkedRef[],
  };
}

/** Coerce an override `ref` (string href or object) into a SourceRef. */
function toRef(ref: string | Partial<SourceRef>, extra: Partial<SourceRef> = {}): SourceRef {
  const base = typeof ref === 'string' ? { kind: 'kg', href: ref } : { kind: 'kg', href: '', ...ref };
  return { ...base, ...extra };
}

/**
 * Apply human overrides to a graph by injecting synthetic identity claims and
 * linked references onto the targeted nodes — additively, before any engine
 * runs. Returns a new graph; the input is not mutated. A null/empty override is
 * a clean no-op (returns the same graph reference).
 *
 * @param {{ nodes: object[] }} graph
 * @param {{ identityClaims?: object[], linkedRefs?: object[] }|null} overrides
 * @returns {{ nodes: object[] }}
 */
export function applyOverrides(graph: KBGraph, overrides: NormalizedOverrides | null | undefined): KBGraph {
  if (!overrides) return graph;
  const { identityClaims = [], linkedRefs = [] } = overrides;
  if (identityClaims.length === 0 && linkedRefs.length === 0) return graph;

  const claimsByNode = new Map<string, IdentityClaim[]>();
  for (const o of identityClaims) {
    const entry: IdentityClaim = { claim: o.claim, ref: toRef(o.ref) };
    if (o.source != null) entry.source = o.source;
    if (o.basis != null) entry.basis = o.basis;
    const nodeClaims = claimsByNode.get(o.node) ?? [];
    nodeClaims.push(entry);
    claimsByNode.set(o.node, nodeClaims);
  }
  const refsByNode = new Map<string, SourceRef[]>();
  for (const o of linkedRefs) {
    const ref = toRef(o.ref ?? { href: o.href ?? '' }, {});
    if (o.resourceKind != null) ref.resourceKind = o.resourceKind;
    if (o.role != null) ref.role = o.role;
    const nodeRefs = refsByNode.get(o.node) ?? [];
    nodeRefs.push(ref);
    refsByNode.set(o.node, nodeRefs);
  }

  const nodes = (graph.nodes ?? []).map((n) => {
    const addClaims = claimsByNode.get(n.id);
    const addRefs = refsByNode.get(n.id);
    if (!addClaims && !addRefs) return n;
    const next = { ...n };
    if (addClaims) next.identityClaims = [...(n.identityClaims ?? []), ...addClaims];
    if (addRefs) next.linkedRefs = [...(n.linkedRefs ?? []), ...addRefs];
    return next;
  });
  return { ...graph, nodes };
}

/**
 * Run the full connect pipeline over a graph: apply overrides, then
 * edge-mint → conflation → SoR-precedence. Pure and deterministic.
 *
 * @param {{ nodes: object[], edges?: object[] }} graph
 * @param {object} [opts]
 * @param {{ identityClaims?: object[], linkedRefs?: object[] }|null} [opts.overrides]
 * @param {object} [opts.config]      KBConfig (precedence read from `config.precedence`).
 * @param {object} [opts.precedence]  Direct SourcePrecedenceConfig override.
 * @returns {{ graph: object, minted: object[], groups: object[], warnings: string[],
 *            precedenceMap: object[], stats: object }}
 */
export function runConnect(graph: ConnectGraph, opts: RunConnectOptions = {}): RunConnectResult {
  // The downstream engines currently expose narrower structural input types than the full graph.
  const withOverrides = applyOverrides(graph as unknown as KBGraph, opts.overrides);
  const mint = mintReferenceEdges(withOverrides as unknown as Parameters<typeof mintReferenceEdges>[0]);
  const conf = conflateReferents(mint.graph as unknown as Parameters<typeof conflateReferents>[0]);
  const prec = resolvePrecedence(conf.graph, { config: opts.config, precedence: opts.precedence });
  const precedenceNodes =
    (prec.graph.nodes ?? []) as unknown as Array<KBNode & { precedence?: PrecedenceInfo }>;

  const precedenceMap = precedenceNodes
    .filter((n: KBNode & { precedence?: PrecedenceInfo }) => n.precedence)
    .map((n: KBNode & { precedence?: PrecedenceInfo }) => ({
      node: n.id,
      ...(n.precedence?.resolved ? { resolved: n.precedence.resolved } : {}),
      ...(n.precedence?.conflicts ? { conflicts: n.precedence.conflicts } : {}),
    }))
    .sort((a: PrecedenceEntry, b: PrecedenceEntry) => cmp(a.node, b.node));

  return {
    graph: prec.graph,
    minted: mint.minted,
    groups: conf.groups,
    warnings: conf.warnings,
    precedenceMap,
    stats: {
      mintedEdges: mint.minted.length,
      conflatedGroups: conf.groups.length,
      contradictions: conf.stats.contradictions,
      precedenceResolved: prec.stats.fieldsResolved,
      precedenceConflicts: prec.stats.fieldsConflicted,
    },
  };
}

/**
 * Serialize a {@link runConnect} result into the three canonical artifact byte
 * strings (filename → bytes). Sorted keys, trailing newline, no timestamps.
 *
 * @param {ReturnType<typeof runConnect>} result
 * @returns {Record<string, string>}
 */
export function serializeConnectArtifacts(result: RunConnectResult): Record<string, string> {
  return {
    [MINTED_EDGES_FILE]: canonicalStringify(result.minted),
    [CONFLATION_MAP_FILE]: canonicalStringify({
      groups: result.groups,
      warnings: result.warnings,
    }),
    [PRECEDENCE_MAP_FILE]: canonicalStringify(result.precedenceMap),
  };
}

/**
 * Load + normalize the human override file. Missing or empty ⇒ null (no-op).
 *
 * @param {string} dir  The `.kbx/connection` directory.
 * @returns {{ identityClaims: object[], linkedRefs: object[] }|null}
 */
export function loadOverrides(dir: string): NormalizedOverrides | null {
  const path = resolve(dir, OVERRIDES_FILE);
  if (!existsSync(path)) return null;
  const raw = readFileSync(path, 'utf-8').trim();
  if (raw === '') return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new ConnectError(
      `${OVERRIDES_FILE} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
      'OVERRIDES_INVALID'
    );
  }
  return normalizeOverrides(parsed);
}

/**
 * Write the generated artifacts into `dir` (creating it). The override file is
 * never touched. Skips files whose committed bytes already match (idempotent).
 *
 * @param {string} dir
 * @param {Record<string,string>} artifacts  filename → bytes
 * @returns {Array<{ file: string, status: 'created'|'updated'|'unchanged' }>}
 */
export function writeConnectArtifacts(
  dir: string,
  artifacts: Record<string, string>,
): Array<{ file: string; status: ArtifactStatus }> {
  mkdirSync(dir, { recursive: true });
  const report: Array<{ file: string; status: ArtifactStatus }> = [];
  for (const file of ARTIFACT_FILES) {
    const bytes = artifacts[file];
    const path = resolve(dir, file);
    const existed = existsSync(path);
    const current = existed ? readFileSync(path, 'utf-8') : null;
    if (current === bytes) {
      report.push({ file, status: 'unchanged' });
      continue;
    }
    writeFileSync(path, bytes, 'utf-8');
    report.push({ file, status: existed ? 'updated' : 'created' });
  }
  return report;
}

/**
 * Byte-for-byte parity check of the committed artifacts against freshly
 * generated bytes. Mirrors `derive --check`.
 *
 * @param {string} dir
 * @param {Record<string,string>} artifacts  filename → expected bytes
 * @returns {{ ok: boolean, drift: Array<{ file: string, reason: string }> }}
 */
export function checkConnectArtifacts(
  dir: string,
  artifacts: Record<string, string>,
): { ok: boolean; drift: Array<{ file: string; reason: string }> } {
  const drift: Array<{ file: string; reason: string }> = [];
  for (const file of ARTIFACT_FILES) {
    const path = resolve(dir, file);
    if (!existsSync(path)) {
      drift.push({ file, reason: `missing committed artifact (run \`kbx connect\`)` });
      continue;
    }
    const committed = readFileSync(path, 'utf-8');
    if (committed !== artifacts[file]) {
      drift.push({
        file,
        reason: `committed bytes differ from a fresh deterministic emit (${committed.length} vs ${artifacts[file].length} bytes)`,
      });
    }
  }
  return { ok: drift.length === 0, drift };
}
