/**
 * kbx scaffold — Create a new content/<slug>.md skeleton with valid
 * frontmatter and a writer-prompt placeholder.
 *
 * Usage:
 *   kbx scaffold <slug> --cluster <id> [--parent <id>] [--title "..."]
 *                              [--emoji "..."] [--content <dir>] [--force]
 *
 * Examples:
 *   kbx scaffold auth-flow --cluster security
 *   kbx scaffold worker-pool --cluster core --parent runtime --title "Worker Pool"
 */

import { resolve } from 'node:path';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { inferIcon } from '../lib/transform.js';
import { resolveContentDir } from '../lib/kb-env.js';

function parseArgs(args) {
  const out = {
    slug: null,
    cluster: null,
    parent: null,
    title: null,
    emoji: null,
    content: null,
    force: false,
  };
  const positional = [];
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--cluster') out.cluster = args[++i];
    else if (a.startsWith('--cluster=')) out.cluster = a.slice('--cluster='.length);
    else if (a === '--parent') out.parent = args[++i];
    else if (a.startsWith('--parent=')) out.parent = a.slice('--parent='.length);
    else if (a === '--title') out.title = args[++i];
    else if (a.startsWith('--title=')) out.title = a.slice('--title='.length);
    else if (a === '--emoji') out.emoji = args[++i];
    else if (a.startsWith('--emoji=')) out.emoji = a.slice('--emoji='.length);
    else if (a === '--content') out.content = args[++i];
    else if (a.startsWith('--content=')) out.content = a.slice('--content='.length);
    else if (a === '--force' || a === '-f') out.force = true;
    else if (!a.startsWith('--')) positional.push(a);
  }
  if (positional[0]) out.slug = positional[0];
  return out;
}

function toTitle(slug) {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function printUsage() {
  console.error(
    'Usage: kbx scaffold <slug> --cluster <id> [--parent <id>] [--title "..."] [--emoji "..."]',
  );
}

export default async function scaffoldCommand(args) {
  const opts = parseArgs(args);

  if (!opts.slug) {
    console.error('error: <slug> is required');
    printUsage();
    process.exit(2);
  }
  if (!SLUG_RE.test(opts.slug)) {
    console.error(`error: slug "${opts.slug}" must be kebab-case (lowercase, hyphens)`);
    process.exit(2);
  }
  if (!opts.cluster) {
    console.error('error: --cluster is required');
    printUsage();
    process.exit(2);
  }

  const cwd = process.cwd();
  const { contentDir } = resolveContentDir(cwd, opts.content);

  mkdirSync(contentDir, { recursive: true });

  const filePath = resolve(contentDir, `${opts.slug}.md`);
  if (existsSync(filePath) && !opts.force) {
    console.error(`error: ${filePath} already exists (use --force to overwrite)`);
    process.exit(1);
  }

  const title = opts.title || toTitle(opts.slug);
  const emoji = opts.emoji || inferIcon(title, opts.cluster);

  const frontmatter = ['---', `id: "${opts.slug}"`, `title: "${title}"`, `emoji: "${emoji}"`, `cluster: ${opts.cluster}`];
  if (opts.parent) frontmatter.push(`parent: "${opts.parent}"`);
  frontmatter.push('connections: []');
  frontmatter.push('---');

  const body = [
    '',
    `# ${title}`,
    '',
    '<!--',
    'kb-writer brief:',
    '  - Read the cited source files thoroughly before writing.',
    '  - Cite specific lines with [path:line](url) or (path:line).',
    '  - Include at least two diagram types (graph + sequence/state/er).',
    '  - Replace this placeholder with rich, evidence-backed content.',
    '-->',
    '',
    '_Content to be generated by the kb-writer playbook._',
    '',
  ].join('\n');

  writeFileSync(filePath, frontmatter.join('\n') + '\n' + body, 'utf-8');

  console.log(`✓ Created ${filePath}`);
  console.log('');
  console.log('Next steps:');
  console.log(`  1. Open ${opts.slug}.md and follow the kb-writer playbook to fill in content.`);
  console.log(`  2. Add a connection by editing the connections: list in the frontmatter.`);
  console.log(`  3. Run: kbx audit   # verify frontmatter is valid`);
  console.log('');
}


