#!/usr/bin/env node
/**
 * Dogfood preview: build a kbexplorer over kbexplorer-cli itself.
 *
 * - Vendors the explorer template into ./.kbexplorer (no submodule).
 * - Writes .env.kbexplorer pointing at this repo + the local content/ dir.
 * - Starts `node bin/cli.js dev` and forwards stdio.
 *
 * Usage:
 *   node scripts/preview-self-kb.js
 */

import { execFileSync, spawn } from 'node:child_process';
import { existsSync, mkdirSync, rmSync, writeFileSync, cpSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const APP_DIR = join(REPO_ROOT, '.kbexplorer');
const ENV_FILE = join(REPO_ROOT, '.env.kbexplorer');
const TEMPLATE_URL = 'https://github.com/anokye-labs/kbexplorer-template.git';

function log(msg) { console.log(`[preview] ${msg}`); }

function vendorTemplate() {
  if (existsSync(join(APP_DIR, 'package.json'))) {
    log('.kbexplorer/ already vendored; skipping clone');
    return;
  }
  log('Cloning template (shallow)…');
  execFileSync('git', ['clone', '--depth=1', TEMPLATE_URL, APP_DIR], {
    stdio: 'inherit',
    cwd: REPO_ROOT,
  });
  rmSync(join(APP_DIR, '.git'), { recursive: true, force: true });
  log('Installing template dependencies…');
  execFileSync(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['install'], {
    stdio: 'inherit',
    cwd: APP_DIR,
    shell: process.platform === 'win32',
  });
}

function ensureEnv() {
  if (existsSync(ENV_FILE)) {
    log('.env.kbexplorer already present; leaving as-is');
    return;
  }
  const body = [
    '# Auto-generated by scripts/preview-self-kb.js',
    'VITE_KB_OWNER=anokye-labs',
    'VITE_KB_REPO=kbexplorer-cli',
    'VITE_KB_BRANCH=main',
    'VITE_KB_TITLE=kbexplorer-cli',
    'VITE_KB_PATH=content',
    '',
  ].join('\n');
  writeFileSync(ENV_FILE, body, 'utf8');
  log('Wrote .env.kbexplorer');
}

function ensureScreenshotDir() {
  mkdirSync(join(REPO_ROOT, 'dist-screenshots'), { recursive: true });
}

function syncContent() {
  // Workaround for a template bug: its detectHostRoot() only recognizes a
  // host repo when the host's package.json#name === 'kbexplorer'. Our
  // package is '@anokye-labs/kbexplorer', so the template's manifest
  // generator silently falls back to scanning its own bundled demo
  // content/. Until that detection is fixed upstream, copy our authored
  // content/ into .kbexplorer/content/ so the template's plugin reads it.
  const srcContent = join(REPO_ROOT, 'content');
  const dstContent = join(APP_DIR, 'content');
  if (!existsSync(srcContent)) {
    log('No content/ in repo; skipping content sync');
    return;
  }
  log('Syncing content/ → .kbexplorer/content/');
  rmSync(dstContent, { recursive: true, force: true });
  cpSync(srcContent, dstContent, { recursive: true });
}

function startDev(extraArgs) {
  log('Starting dev server (node bin/cli.js dev)…');
  const child = spawn(process.execPath, [join('bin', 'cli.js'), 'dev', ...extraArgs], {
    cwd: REPO_ROOT,
    stdio: 'inherit',
  });
  child.on('exit', (code) => process.exit(code ?? 0));
  process.on('SIGINT', () => child.kill('SIGINT'));
  process.on('SIGTERM', () => child.kill('SIGTERM'));
}

vendorTemplate();
ensureEnv();
syncContent();
ensureScreenshotDir();
startDev(process.argv.slice(2));
