/**
 * Sampled-content provenance — the "record provenance for sampled content" half
 * of the consent rules (PE3-F3).
 *
 * The sampling bridge blurs control: an action drives an agent, which drives a
 * model, which produces files. Once model-generated bytes land in the graph we
 * must be able to answer *"what produced this, and from which inputs?"* without
 * reaching for a clock. This module stamps that answer onto generated changes
 * using the **same {@link Derivation}/{@link SourceRef} contract** the rest of
 * the system already consumes (see `src/lib/affected-graph.js`, which recomputes
 * off `derivation.inputs[].contentHash` — never a timestamp).
 *
 * Everything here is **pure, deterministic, and timestamp-free**: identical
 * generator + inputs → byte-identical provenance, so re-emitting a generated
 * artifact is idempotent and the drift gate stays meaningful. It is also
 * **protocol-neutral** — no MCP, JSON-RPC, canvas, or transport code, exactly
 * like the rest of `src/affordances/`.
 *
 *   - {@link sampledSourceRef}  — normalise one provenance input to a SourceRef.
 *   - {@link buildDerivation}   — assemble a deterministic Derivation for a
 *                                 sample-class action (generator + sorted inputs).
 *   - {@link stampProvenance}   — non-mutating attach of a Derivation onto a
 *                                 generated change record.
 *
 * @module src/affordances/provenance
 */

/** Canonical generator id for the job-layer generation runtime (sample-class). */
export const SAMPLE_GENERATOR = '@anokye-labs/kbx generate';

export interface SourceRef {
  href: string;
  contentHash?: Record<string, unknown>;
}

export interface Derivation {
  generator: string;
  actionClass: 'sample';
  inputs: SourceRef[];
  inputDigest?: string;
}

interface SourceRefInput {
  href?: unknown;
  contentHash?: unknown;
}

export interface BuildDerivationSpec {
  generator?: string;
  inputs?: Array<string | SourceRefInput>;
  request?: unknown;
}

/**
 * Stable, key-sorted JSON used to compare/derive provenance deterministically.
 * Mirrors the canonicaliser the job store uses for ids: no timestamps, sorted
 * keys, arrays keep order.
 *
 * @param {*} value
 * @returns {string}
 */
function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`;
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}:${canonicalJson(record[k])}`).join(',')}}`;
  }
  return JSON.stringify(value === undefined ? null : value);
}

/**
 * Normalise a raw provenance input into a {@link SourceRef}. Accepts either a
 * plain href string or an object carrying `{ href, contentHash?, ... }` (the
 * shape `extractInputRefs` already reads). Anything without a usable href is
 * dropped by {@link buildDerivation}; this returns `null` for those.
 *
 * The `contentHash` (when present) is passed through verbatim — it is the
 * canonical recompute signal, so we neither invent nor strip it.
 *
 * @param {string|object} input
 * @returns {{href: string, contentHash?: object}|null}
 */
export function sampledSourceRef(input: string | SourceRefInput | null | undefined): SourceRef | null {
  if (typeof input === 'string') {
    const href = input.trim();
    return href ? { href } : null;
  }
  if (input && typeof input === 'object') {
    const href = typeof input.href === 'string' ? input.href.trim() : '';
    if (!href) return null;
    const ref: SourceRef = { href };
    if (input.contentHash && typeof input.contentHash === 'object' && !Array.isArray(input.contentHash)) {
      ref.contentHash = input.contentHash as Record<string, unknown>;
    }
    return ref;
  }
  return null;
}

/**
 * Build a deterministic {@link Derivation} describing how a piece of sampled
 * (model-generated) content was produced. The result is timestamp-free and its
 * `inputs` are sorted by `href` (then by canonical hash) so identical
 * generator + inputs always yield byte-identical provenance.
 *
 * @param {object} spec
 * @param {string} [spec.generator=SAMPLE_GENERATOR]  Producing tool id.
 * @param {Array<string|object>} [spec.inputs=[]]     Provenance inputs (SourceRef-ish).
 * @param {object} [spec.request]  The opaque generation request; folded into the
 *        derivation as a deterministic `inputDigest` so a changed request is a
 *        provenance change without leaking the (possibly large) request bytes.
 * @returns {{generator: string, actionClass: 'sample', inputs: Array<{href: string, contentHash?: object}>, inputDigest?: string}}
 */
export function buildDerivation({
  generator = SAMPLE_GENERATOR,
  inputs = [],
  request,
}: BuildDerivationSpec = {}): Derivation {
  const refs = (Array.isArray(inputs) ? inputs : [])
    .map(sampledSourceRef)
    .filter((ref): ref is SourceRef => ref !== null);

  // Sort by href, then by canonical hash, so order-insensitive inputs canonicalise.
  refs.sort((a, b) => {
    if (a.href !== b.href) return a.href < b.href ? -1 : 1;
    const ah = canonicalJson(a.contentHash ?? null);
    const bh = canonicalJson(b.contentHash ?? null);
    return ah < bh ? -1 : ah > bh ? 1 : 0;
  });

  // De-duplicate identical refs (same href + hash) after sorting.
  const deduped: SourceRef[] = [];
  let prev = '';
  for (const ref of refs) {
    const key = canonicalJson(ref);
    if (key !== prev) deduped.push(ref);
    prev = key;
  }

  const derivation: Derivation = {
    generator,
    actionClass: 'sample',
    inputs: deduped,
  };
  if (request !== undefined) {
    derivation.inputDigest = canonicalJson(request);
  }
  return derivation;
}

/**
 * Attach a {@link Derivation} to a generated change record **without mutating**
 * the original. The provenance is recorded at the top-level `derivation` key —
 * the canonical surface `extractInputRefs` reads (`derivation.inputs[]`) — so the
 * affected/drift engines see model-generated content as derived from its declared
 * inputs. Any pre-existing `provenance` bag on the change is preserved untouched.
 *
 * @param {object} change       A `{ path, contents }`-style change record.
 * @param {object} derivation   A {@link buildDerivation} result.
 * @returns {object} A shallow copy of `change` with `derivation` set.
 */
export function stampProvenance<T extends Record<string, unknown>>(
  change: T,
  derivation: Derivation | null | undefined,
): T & { derivation?: Derivation } {
  if (!change || typeof change !== 'object') {
    return change as T & { derivation?: Derivation };
  }
  if (!derivation || typeof derivation !== 'object') return { ...change };
  return { ...change, derivation };
}

export { canonicalJson as canonicalProvenanceJson };
